urls.py
from django.conf.urls.defaults import *
from django.contrib.auth import views as auth_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from gabaluu.synopsis import views as synopsis_views
from gabaluu.account import views as account_views


import os.path

PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))

feeds = {
    'popular': synopsis_views.PopularFeed,
    'recent': synopsis_views.RecentFeed,
}


urlpatterns = patterns('',
    (r'^auth/$', account_views.auth),                   
    (r'^admin/', include('django.contrib.admin.urls')),
    (r'^login/$', auth_views.login, dict(template_name='login.html')),
    (r'^accounts/login/$', auth_views.login, dict(template_name='login.html')),
    (r'^logout/$', auth_views.logout, dict(next_page='/')),
    (r'^signup/$', account_views.signup),
    (r'^accounts/profile/$', account_views.profile),
    (r'^forgot/password/$', auth_views.password_reset),
    (r'^forgot/password/done/$', auth_views.password_reset_done),
    (r'^password/change/$', auth_views.password_change),
    (r'^password/change/done/$', auth_views.password_change_done),
    (r'^$', synopsis_views.index),
    (r'^popular/$', synopsis_views.popular),
    (r'^popular/(?P<current_page>\w+)/$', synopsis_views.popular),
    (r'^recent/$', synopsis_views.recent),
    (r'^recent/(?P<current_page>\w+)/$', synopsis_views.recent),
    (r'^tags/(?P<tag>\w+)/$', synopsis_views.tagged),
    (r'^tags/(?P<tag>\w+)/(?P<current_page>\w+)/$', synopsis_views.tagged),
    (r'^sites/(?P<site>\w+)/$', synopsis_views.sites),
    (r'^search/$', synopsis_views.synopsis_search),
    (r'^members/$', account_views.members),
    (r'^terms/$', synopsis_views.terms),
    (r'^privacy/$', synopsis_views.privacy),
    (r'^about/$', synopsis_views.about),
    (r'^profile/(?P<username>\w+)/$', account_views.user_profile_posted),
    (r'^profile/(?P<username>\w+)/voted/$', account_views.user_profile_voted),
    (r'^profile/(?P<username>\w+)/commented/$', account_views.user_profile_commented),    
    (r'^synopsis/(?P<synopsis_id>\w+)/vote/$', synopsis_views.synopsis_vote),
    (r'^synopsis/new/$', synopsis_views.synopsis_new),
    (r'^synopsis/(?P<permalink>\w+)/edit/$', synopsis_views.synopsis_edit),
    (r'^synopsis/(?P<permalink>\w+)/$', synopsis_views.synopsis_detail),
    (r'^synopsis/(?P<synopsis_id>\w+)/comments/create/$', synopsis_views.comment_create),
    (r'^synopsis/(?P<synopsis_id>\w+)/comments/(?P<comment_id>\w+)/create/$', synopsis_views.comment_create),
    (r'^synopsis/(?P<synopsis_id>\w+)/link/$', synopsis_views.synopsis_link),
    (r'^synopsis/(?P<permalink>\w+)/preview/$', synopsis_views.synopsis_preview),
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds})
)

# Use Django to serve media files only during development.
# Settings.py for Production: DEBUG = FALSE
if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
                             dict(document_root=os.path.join(PROJECT_PATH, 'media'))),
    )
                            

synopsis/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from django.core.paginator import ObjectPaginator, InvalidPage
import re
import urlparse
from datetime import datetime, timedelta
from gabaluu.form_choices import COMMENT_TYPES

class Site(object):
    pass


class Tag(models.Model):
    name      = models.CharField(maxlength=100)
    count    = models.IntegerField()
    
    
    def _get_font_size(self):
        count = self.count + 10
        return "font-size: %spx;" % count
    font_size = property(_get_font_size)

    @classmethod
    def find_all(cls, site):
        return Tag.objects.all()

    @classmethod
    def find_or_create(cls, name, new_synopsis=True):      
        tag, created = Tag.objects.get_or_create(name=name, defaults={'count': 0 })
        
        if new_synopsis or (not new_synopsis and created):
            tag.count = tag.count + 1
         
        return tag

    @classmethod
    def find_by(cls, name):
        tags = Tag.objects.filter(name=str(name).strip())
        if tags.count() == 0:
            return None
        return tags[0]

    @classmethod
    def parse(cls, tags):
     """
        Parses a comma separated list of tags into 
        tag names handles all kinds of different tags. 
        (comma seperated, space seperated)
        Todo...Enhance to support more formats (in quotes)
     """
     return re.split('[,\\s]+', tags)



class Synopsis(models.Model):
     """
     A synopsis of a web resource.

     """
     title = models.CharField(maxlength=50)
     permalink = models.CharField(maxlength=100)
     text = models.CharField(maxlength=5000)
     article_site_url = models.CharField(maxlength=500)
     article_url = models.CharField(maxlength=500)
     pub_date = models.DateTimeField(editable=False)
     updated_date = models.DateTimeField(editable=False, blank=True, null=True)
     author = models.ForeignKey(User, related_name='author_id')
     tags = models.ManyToManyField(Tag)
     score = models.IntegerField()
     
     
     def __str__( self ):
         return self.title
     
     def get_absolute_url(self):
         return "http://zenopsis.com/synopsis/%s/" % self.permalink
     
     def is_author_of_synopsis(self, user):
         if self.author.username == user.username:
             return True
         return False
         
     @classmethod
     def create_permalink(cls, title, article_url):
         url_parts = urlparse.urlparse(article_url)
         title = Synopsis._remove_special_char(title)
         return "_".join((url_parts[1].replace('.', '_'), title))
         
     @classmethod   
     def _remove_special_char(cls, string):
         string = string.strip().replace(' ', '_')
         string = string.replace("'", "")
         string = string.replace("$", "")
         string = string.replace("&", "")
         string = string.replace("<", "")
         string = string.replace(">", "")
         string = string.replace("*", "")
         string = string.replace("@", "")
         string = string.replace(".", "")
         string = string.replace(":", "")
         string = string.replace("|", "")
         string = string.replace("~", "")
         string = string.replace("`", "")
         string = string.replace("(", "")
         string = string.replace(")", "")
         string = string.replace("%", "")
         string = string.replace("#", "")
         string = string.replace("^", "")
         string = string.replace("?", "")
         string = string.replace("/", "")
         string = string.replace("{", "")
         string = string.replace("}", "")
         string = string.replace(",", "")
         string = string.replace(";", "")
         string = string.replace("!", "")
         string = string.replace("+", "")
         string = string.replace("=", "")
         string = string.replace("-", "_")
         return string
 
     @classmethod
     def _run_query(cls, query, pagination=False, current_page=0, items_per_page=10):
         if pagination:
             paginator = ObjectPaginator(query, items_per_page)
             synopsis_list = paginator.get_page(current_page)
         else:
             paginator = None
             synopsis_list = query
         return synopsis_list, paginator
         
     @classmethod
     def most_recent(cls, pagination=False, current_page=0, items_per_page=10):
         return Synopsis._run_query(Synopsis.objects.all().order_by('-pub_date'), 
                                    pagination=pagination, 
                                    current_page=current_page, 
                                    items_per_page=items_per_page)
         
     @classmethod
     def popular(cls, pagination=False, current_page=0, items_per_page=10):
         return Synopsis._run_query(Synopsis.objects.all().order_by('-score', '-pub_date'), 
                                    pagination=pagination, 
                                    current_page=current_page, 
                                    items_per_page=items_per_page)
     @classmethod
     def by_tag(cls, tag, pagination=False, current_page=0, items_per_page=10):
         return Synopsis._run_query(Synopsis.objects.filter(tags__name__exact=tag).order_by('-pub_date'), 
                                   pagination=pagination, 
                                   current_page=current_page, 
                                   items_per_page=items_per_page)

     @classmethod
     def user_posted_synopsis_list(cls, user):
         return Synopsis.objects.filter(author=user).order_by('-pub_date')
     
     @classmethod
     def user_voted_synopsis_list(cls, user):
         election_list = Election.objects.filter(user=user).order_by('-date')
         return [election.synopsis for election in election_list]
    
     @classmethod
     def user_commented_synopsis_list(cls, user):
         comment_list = Comment.objects.filter(posted_by=user).order_by('-date')
         return [comment.synopsis for comment in comment_list] 
           
     @classmethod
     def query(cls, query):
         # todo -- improve search logic to search across all model fields
         return Synopsis.objects.filter(title__icontains=query)
           
     @classmethod
     def by_article_site(cls, site): 
         article_site_url = "http://%s" % site.replace('_', '.')     
         return Synopsis.objects.filter(article_site_url=article_site_url).order_by('-pub_date')

     
     def _published(self):
         """Return the synopsis formated published date."""
         return  self.pub_date.strftime('%B %d, %Y')
     published = property(_published)
 
     def _tags_as_string(self):
         tags_string = ""
         for tag in self.tags.all():
             tags_string =  ' '.join((tags_string, tag.name))

         return tags_string.strip()
     tags_as_string = property(_tags_as_string)
 
     def _short_text(self):
         text = "%s <a href='/synopsis/%s'>More >> </a>" % (self.text[:200], 
                                                             self.permalink)
         return text
     short_text = property(_short_text)
 
     def _short_text_preview(self):
         text = "<h2>%s</h2> %s <a href='/synopsis/%s' target='_top'>More >> </a>" % (self.title,
                                                                             self.text[:200], 
                                                                             self.permalink)
         return text
     short_text_preview = property(_short_text_preview)
     
     def _get_comments(self):
         """Return list of comments on this synopsis. """
         return Comment.objects.filter(synopsis=self, type_of="1", reply_to__isnull=True)
     comments = property(_get_comments)
     
     def _number_of_comments(self):
         count = len(Comment.objects.filter(synopsis=self, type_of="1"))
         if count == 1:
             return str(count) + " comment"
         else:
             return str(count) + " comments"
     number_of_comments = property(_number_of_comments)
 
     def _get_revisions(self):
         """Return list of revision comments on this synopsis. """
         return Comment.objects.filter(synopsis=self, type_of="2")
     revisions = property(_get_revisions)
 
     def _get_votes(self):
         count = self.score
         if count == 1:
             return str(count) + " vote"
         else:
             return str(count) + " votes"
     votes = property(_get_votes)
     
    
     @classmethod
     def article_site_list(cls):
         from django.db import connection
         cursor = connection.cursor()
         sql = """select article_site_url, count(article_site_url) from synopsis_synopsis 
                  group by article_site_url having count(article_site_url) >= 1 """
         cursor.execute(sql)
         rows = cursor.fetchall()
         site_list = []
         for row in rows:
             url_parts = urlparse.urlparse(row[0])
             site = Site()
             site.key = url_parts[1].replace('.', '_')
             site.url = url_parts[1]
             site.count = row[1]
             site_list.append(site)
         return site_list
         
     @classmethod
     def tag_and_article_site_list(cls):
         site_list = Synopsis.article_site_list()
         tag_list = Tag.objects.all()
         
         tags = []
         for t in tag_list:
            t.uri = "/tags/%s/" % t.name
            tags.append(t)
             
         for site in site_list:
             tag = Tag()
             tag.uri = "/sites/%s/" % site.key
             tag.name = site.key.replace('_', '.')
             tag.name = tag.name.replace('www.', '')
             tag.count = site.count
             tags.append(tag)
         
         return tags


              
class Election(models.Model):
     """
     Map if a user voted on a synopsis.

     """
     synopsis = models.ForeignKey(Synopsis)
     user = models.ForeignKey(User)

synopsis/forms.py
from django import newforms as forms
from django.conf import settings
from django.utils.translation import gettext as _
from datetime import datetime, timedelta
import urlparse
from gabaluu.form_choices import COMMENT_TYPES
from gabaluu.synopsis.models import Synopsis
from gabaluu.synopsis.models import Tag
from gabaluu.synopsis.models import Comment

class SynopsisForm(forms.Form):
    """
    
    The synopsis form.
      
    """
    title = forms.CharField(label=_('Title'), max_length=50, required=True, 
                            widget=forms.TextInput(attrs={"class": "form-text-variable"}))
    text = forms.CharField(label=_('Text'), required=True,
                           widget=forms.Textarea(attrs={"cols": "50", "rows": "80",
                                                        "maxlength": "1000"}))
    article_url = forms.CharField(label=_('Article Url'), max_length=500, required=True, 
                                  widget=forms.TextInput(attrs={"class": "form-text-variable"}))
    tags = forms.CharField(label=_('Tags'), max_length=100, required=False, 
                           widget=forms.TextInput(attrs={"class": "form-text-variable"}))
            
    def save(self, synopsis, author):
        data = self.data
        synopsis.title = data['title']
        synopsis.article_url = data['article_url']
        synopsis.text = data['text']
        synopsis.pub_date = datetime.now()
        synopsis.author = author
        synopsis.score = 0
        synopsis.permalink = Synopsis.create_permalink(title=data['title'], 
                                                      article_url=data['article_url'])
        url_parts = urlparse.urlparse(data['article_url'])
        protocol, domain = url_parts[:2]
        synopsis.article_site_url = '%s://%s' % (protocol, domain)
        
        synopsis.save()
        
        tag_list = Tag.parse(data['tags'])
        for tag_name in tag_list:
            tag = Tag.find_or_create(name=tag_name)
            tag.save()
            synopsis.tags.add(tag)
        
    def update(self, synopsis):
        data = self.data
        synopsis.text = data['text']
        synopsis.updated_date = datetime.now()
        synopsis.save()

        tag_list = Tag.parse(data['tags'])
        for tag_name in tag_list:
            tag = Tag.find_or_create(name=tag_name, new_synopsis=False)
            tag.save()
            synopsis.tags.add(tag)

class CommentForm(forms.Form):
   """

   The comment form.

   """

   def save(self, synopsis, comment_id, posted_by):
       #data = self.cleaned_data
       data = self.data
       text = data['comment']
       type_of = Comment.type_from_friendly_name('Feedback')
       comment = Comment.objects.create(posted_by=posted_by,
                                        text=text, 
                                        date=datetime.now(),
                                        type_of=type_of,
                                        synopsis=synopsis,
                                        reply_to=comment_id)
       return comment

class SearchForm(forms.Form):
   """

   The basic search form.

   """
   search_query = forms.CharField(label=_('Search'), max_length=200, required=True)

   def search(self):
       #data = self.cleaned_data
       data = self.data
       return Synopsis.query(data['search_query'])

templates/synopsis/comment.html
{% load model_tags %}
{% load markup %}

{% if comment %}
    <li>
        <img height="20px" width="20px" src="/site_media/avatars/{{comment.posted_by.get_profile.avatar_filename}}" /> by
        <a href='/profile/{{ comment.posted_by.username}}'>{{ comment.posted_by.username}}</a> on {{comment.formated_date}}
        <br/><br/>
        
        {{comment.text|safe|textile}}
        
        <br/><br/>
        {% if user.is_authenticated %}
            <a href="#" onclick="$('#comment_{{comment.id}}_reply_to').toggle(); return false;">Post reply to comment</a>
        
            {% if comment.comments %}
                | <a href="#" onclick="$('#reply_to_comment_list_{{comment.id}}').toggle(); return false;">replies</a>
            {% endif %}
        {% endif %}
        
  &nbsp;<div id="comment_{{comment.id}}_reply_to" style="display: none;">
             {% render_comment_form  comment.synopsis  comment %}
         </div>
        <br/><br/>
  
        <div id="reply_to_comment_list_{{comment.id}}">
               {% render_comment_list comment.comments user "reply-thread"  %}
        </div>
    </li>
{% endif %}

templates/synopsis/comment_form.html
{% if url %}
    <form class="comment-form" action="{{url}}" 
          method="post">
      
         <textarea id="comment" name="comment" cols="50" rows="10" class="comment"></textarea>
     
         <br/><br/>
        <input type="submit" value="Post comment"  />
        
    </form>
{% endif %}

templates/synopsis/comment_list.html
{% load model_tags %}

<ul class="{{comment_list_css}}">
{% if comment_list %}
    {% for comment in comment_list %}
       {% render_comment comment user %}
    {% endfor %}
{% endif %}
</ul>

templates/synopsis/comment_list_recent.html
{% load model_tags %}
{% load markup %}

<h2>Recent Comments »</h2>
<ul>
{% if comment_list %}
    {% for comment in comment_list %}
       <li>
              <img height="20px" width="20px" src="/site_media/avatars/{{comment.posted_by.get_profile.avatar_filename}}" />
              <a href='/profile/{{ comment.posted_by.username}}'>{{ comment.posted_by.username}}</a> <br/>

              {{comment.short_text|safe|textile}}
          </li>
    {% endfor %}
{% endif %}
</ul>

templates/synopsis/synopsis.html
{% load model_tags %}
{% load markup %}

{% if synopsis %}
    <div id="synopsis-{{synopsis.id}}">
        <h2>     
         <a class="vote-up" href="/synopsis/{{synopsis.id}}/vote/" {{has_voted|safe}} title="Vote">
             <img height="13px" width="15px" border="0" src="/site_media/images/check.png" /> 
        </a>
        {% if detail %}
            {{synopsis.title}}</h2><a href="/synopsis/{{synopsis.id}}/link">Link to this synopsis</a>
            <p>{{synopsis.text|safe|textile}}</p>
        {% else %}
            <a href="/synopsis/{{synopsis.permalink}}">{{synopsis.title}}</a></h2>
            <p>{{synopsis.short_text|safe|textile}}</p>
        {% endif %}
        
        
        <span id="synopsis-{{synopsis.id}}-vote" class="vote-count">{{synopsis.votes}}</span>
        posted by <a href='/profile/{{ synopsis.author.username}}'>{{ synopsis.author.username}}</a>
        <label for="pub_date">on </label>{{synopsis.published}} with
        <a href="/synopsis/{{synopsis.permalink}}#comments-section">{{synopsis.number_of_comments}}</a>
        {% if is_author_of_synopsis %}
            <a href="/synopsis/{{synopsis.permalink}}/edit">edit</a><br/>
        {% endif %}
        {% render_tag_list tag_list %}
        {% if detail %}
            <label for="article_url">Article Url: </label><a href="{{synopsis.article_url}}">{{synopsis.article_url}}</a><br/>
            <label for="article_site_url">Site Url: </label><a href="{{synopsis.article_site_url}}">{{synopsis.article_site_url}}</a><br/>
            
        {% endif %}
        
    </div>
{% endif %}

templates/synopsis/synopsis_article_site_list.html
{% if article_site_list %}
    <div>
        <ul class="list">
        {% for site in article_site_list %}
            <li>
              <a href="/sites/{{site.key}}">{{site.url}}</a> ({{site.count}})<br/>
            </li>
        {% endfor %}
        </ul>
    </div>
{% endif %}

templates/synopsis/synopsis_detail.html
{% extends "__base__.html" %}


{% block content %}

{% load model_tags %}

<br/>
<a href="/popular/">Popular</a> | <a href="/recent/">Most Recent</a> 
<br/><br/>

{% render_synopsis synopsis user "True" %}

<div id="comments-section">
    <h3>Comments</h3>
    {% render_comment_list synopsis.comments user %}

    {% if user.is_authenticated %}
        {% render_comment_form synopsis %}
    {% endif %}
</div>

<br/><br/>

{% endblock %}


{% block content_two %}
<br/>
{% render_tag_list tag_list %}

{% endblock %}


{% block content_three %}
<br/>
<!--{% render_synopsis_article_site_list article_site_list %} -->
{% render_comment_list_recent recent_comment_list user %}

{% endblock %}

templates/synopsis/synopsis_edit.html
{% extends "__base__.html" %}

{% load model_tags %}

{% block content %}
<br/>
<a href="/popular/">Popular</a> | <a href="/recent/">Most Recent</a> 
    <br/><br/>
    <h2>Edit Synopsis </h2>
    <div id="new-form">
        <form action="." method="post" class="form-large">
            {% if form.error_dict %}
                 <p class="error">Please correct the errors below.</p>
            {% endif %}
            
            <h3>{{synopsis.title}}</h3>
   
            <h4><a href="{{synopsis.article_url}}">{{synopsis.article_url}}</a></h4>
            
            <h3>{{synopsis.published}}</h3>
        
            
            {% if form.text.errors %}
              {{ form.text.html_error_list }}
            {% endif %}
            <label for="text">Synopsis:</label><br/> {{ form.text }}<br/><br/>
            
            <div>
                <label for="bodytext" accesskey="3">Tags </label>
                <input id="id_tags" type="text" name="tags" value="{{synopsis.tags_as_string}}" maxlength="100" />
            </div>
            
             <br/>
             <span id="small-fields">
            <input type="submit" value="Update Synopsis" class="submit-button"  />
            </span>&nbsp;
            or &nbsp;
            <a href='/'>Cancel</a>
            
            <br/><br/>

        </form>
    </div>
    
{% endblock %}

{% block content_two %}
<br/><br/><br/><br/><br/>
{% render_textile_help %}

{% endblock %}

templates/synopsis/synopsis_link.html
{% extends "__base__.html" %}

{% block content %}

<p>To link to this synopsis from your site or blog, just copy and paste the following code onto your page.

<div><textarea class="link-code" cols="80" rows="6" readonly>
<script type="text/javascript">
var zenopsis_name = "{{synopsis.permalink}}";
</script>
<script type="text/javascript" 
src="http://zenopsis.com/site_media/js/synopsis-linking.js">
</script></textarea></div>
<br/>
<p>The synopsis link will look like this on your page. Click the down arrow to try it now!</p>
<script type="text/javascript">
var zenopsis_name = "{{synopsis.permalink}}";
</script>
<script type="text/javascript" src="http://zenopsis.com/site_media/js/synopsis-linking.js"></script>
<br/>

{% endblock %}

templates/synopsis/synopsis_list.html
{% load model_tags %}

{% if synopsis_list %}
    <div id="synopsis-list">
        <ol>
        {% for synopsis in synopsis_list %}
            <li>
                {% render_synopsis synopsis user  %}
            </li>
        {% endfor %}
        </ol>
        
        {% if has_previous_page %}
            {% if previous_page_is_first_page %}
                <a href="/{{base_path}}/"><< Back</a>
            {% else %}
                <a href="/{{base_path}}/{{previous_page}}/"><< Back</a>
            {% endif %}
            
        {% endif %}
        
        {% if pages %}
            {% for page in pages %}
                {% if page.is_current %}
                    <span>{{page.number}}</span>&nbsp;
                {% else %}
                    <a href="/{{base_path}}/{{page.number}}/">{{page.number}}</a> &nbsp;
                {% endif %}
            {% endfor %}
        {% endif %}
        
        {% if has_next_page %}
            <a href="/{{base_path}}/{{next_page}}/">Next >> </a>
        {% endif %}
        <br/><br/>
    </div>
{% endif %}

templates/synopsis/synopsis_new.html
{% extends "__base__.html" %}

{% load model_tags %}

{% block content %}
<br/>
<a href="/popular/">Popular</a> | <a href="/recent/">Most Recent</a> 
    <br/><br/>
    <h2>Submit a New Synopsis </h2>
    <div id="new-form">
        <form action="." method="post" class="form-large">
            {% if form.error_dict %}
                 <p class="error">Please correct the errors below.</p>
            {% endif %}
            
            {% if form.article_url.errors %}
              {{ form.article_url.html_error_list }}
            {% endif %}
            
            <div>
                <label for="title" accesskey="2">Enter the URL of the Article</label>
                {{ form.article_url }}<br/><br/>
            </div>
            

            {% if form.title.errors %}
              {{ form.title.html_error_list }}
            {% endif %}
            
            <div>
                <em class="field-count"><span id="titleCounter">50</span> Characters Left</em>
                <label for="title" accesskey="2">Article Title <span>(Be descriptive with the title.)</span></label>
                {{ form.title }}<br/>
            </div>
            

            {% if form.text.errors %}
              {{ form.text.html_error_list }}
            {% endif %}
            <div>
                <em class="field-count"><span id="bodytextCounter">1000</span> Characters Left</em>
                <label for="bodytext" accesskey="3">Synopsis <span>(Write your summary of the article.)</span></label>
                 {{ form.text }}<br/>
            </div>
            {% if form.tags.errors %}
              {{ form.tags.html_error_list }}
            {% endif %}
            <div>
                <label for="bodytext" accesskey="3">Tags <span>(Tags help people search for your synopsis.)</span></label>
                {{ form.tags }}
            </div>
            
             <br/>
             
             {% if captcha_error %}
                 {{captcha_error|safe}}
             {% endif %}
            
            <label for="bodytext" accesskey="3">Are You Human?<span>(Enter the two words you see in the image.)</span></label>
            {{captcha_form|safe}}
             
             <br/>
             <span id="small-fields">
            <input type="submit" value="Submit Synopsis" class="submit-button"  />
            </span>&nbsp;
            or &nbsp;
            <a href='/'>Cancel</a>
            
            <br/><br/>

        </form>
        
    </div>
    
{% endblock %}

{% block content_two %}
<br/><br/><br/><br/><br/>
{% render_textile_help %}

{% endblock %}

templates/synopsis/synopsis_preview.html
<link rel="stylesheet" type="text/css" href="/site_media/css/style.css">

<!-- Use safe filter to turn off auto-escaping. -->
<p>{{synopsis.short_text_preview|safe}}</p>

templates/synopsis/tag_list.html
{% if tag_list %}
    <div>
        <ul class="list">
        {% for tag in tag_list %}
            <span style="{{tag.font_size}}">
              <a title="{{tag.count}}" href="{{tag.uri}}">{{tag.name}}</a> 
            </span>
        {% endfor %}
        </ul>
    </div>
{% endif %}

templates/synopsis/textile_help.html
<div id="textile_help">
	<h3>Textile Shortcuts</h3>	<p>Formatting:<br />
	&#95;<em>emphasis</em>&#95;<br />
	&#42;<strong>strong</strong>&#42;<br />
	&#63;&#63;<cite>citation</cite>&#63;&#63;<br />
	&#45;<del>deleted text</del>&#45;<br />
	&#43;<ins>inserted text</ins>&#43;<br />
	&#94;<sup>superscript</sup>&#94;<br />
	&#64;<code>code</code>&#64;</p>
	h1. Large Header <br/>
    h2. Med Header <br/>
	

		<p>Hyperlink:<br />
	&#34;link text&#34;:http://link.url</p>

		<p>Image:<br />
	&#33;http://image.url&#33;</p>

		<p>To define an acronym:<br />
	<span class="caps">ABC</span>&#40;Always Be Closing&#41;</p>

		<p>To define a bulleted list:<br />
	<pre>
	* item one
	* item two
	** item two a
	** item two b
	* item three</pre></p>

	    <p>To define an ordered list:<br />
	<pre>
	# item one
	# item two
	# item three</pre></p>

 </div>